### PR TITLE
Improve tr locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by aleksey-saenko** [comment]
Merged, thanks. Version 1.4.3 was published with the first version of translation. These changes don't require an immediate app update (hot fix), right?

**Comment by mikropsoft** [comment]
> Merged, thanks. Version 1.4.3 was published with the first version of translation. These changes don't require an immediate app update (hot fix), right?

It's not a big deal, I changed the main word, but there is no hurry. It's up to you :)

**Comment by mikropsoft** [comment]
@aleksey-saenko By the way, I apologize, the "forward" string must have been deleted. I couldn't add it because I didn't see the last commit. I realized it now. you can add it.

**Comment by aleksey-saenko** [comment]
Cool, then I will release this update when other changes are ready.
And no problem, I'll add the missed line myself.

**Pull request merged**
