### PR TITLE
Translation: Add PT-BR

### PR DESCRIPTION
**Pull request by lucasmz-dev**
https://codeberg.org/lucasmz/translation-suggestions/issues/25

### CODE REVIEW

**Comment by aleksey-saenko** [comment]
Hi. Thanks for providing the Portuguese translation. Nice work!
Could you also add translations for the files `full_description.txt`, `short_description.txt`? These files hold the metadata for the D-Froid app. You can find these files in the `fastlane/metadata/android/en-US/`. Please create a new folder (named `pt-BR`) next to `en-US` and put the translated files there. This would be greatly appreciated!
There's no need to translate the changelogs or provide screenshots, as it would be hard for us to keep them updated.

**Comment by lucasmz-dev** [comment]
Oh I forgot about that! Thanks for reminding this!

**Comment by lucasmz-dev** [comment]
In the future I can do screenshots if you'd like and then if you feel they're out of date just remove them, only if you'd like to though

**Comment by lucasmz-dev** [comment]
Done!

**Comment by aleksey-saenko** [comment]
Thank you! It's great that the app has been localized for such a large region.

**Pull request merged**
