### PR TITLE
Add Czech language

### PR DESCRIPTION
**Pull request by Fjuro**

### CODE REVIEW

**Comment by aleksey-saenko** [comment]
@Fjuro Hi, thanks for providing the Czech translation. In my view, everything is fine here.
Please delete any strings that have the attribute "translatable=false" and we will merge this.

**Comment by aleksey-saenko** [comment]
I've added a few new strings in recent commits. It would be great if you could provide translations for them as well.

**Comment by Fjuro** [comment]
Both done!

**Comment by aleksey-saenko** [comment]
Nice work! The translation will be included in v1.1.2. Thanks!

**Comment by Fjuro** [comment]
Thank you, too!

**Comment by aleksey-saenko** [comment]
@Fjuro 
Hi there! The app is now hosted on [Weblate](https://hosted.weblate.org/projects/audile/). If you have a moment to update the translation, I would greatly appreciate it.

**Pull request merged**
