### PR TITLE
Add turkish locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by mikropsoft** [comment]
> Hi again, Thanks a lot providing the Turkish translation, it's a great job.
> 
> Could you also add translations for the files `full_description.txt`, `short_description.txt`? These files hold the metadata for the D-Froid app. You can find these files in the `fastlane/metadata/android/en-US/`. Please create a new folder (named `tr` for Turkish) next to `en-US` and put the translated files there. This would be greatly appreciated! There's no need to translate the changelogs or provide screenshots, as it would be hard for us to keep them updated. Also, please remove any strings that have the attribute `translatable=false` from strings.xml.

sure, it will be ready soon :)

**Comment by mikropsoft** [comment]
Also the strings "false" are not translated, thanks

**Comment by aleksey-saenko** [comment]
Thanks for providing additional files.
I've added escaping for special characters ([docs](https://developer.android.com/guide/topics/resources/string-resource#FormattingAndStyling)), removed redundant non-translatable strings, and made some minor fixes. You can verify if everything is okay; if so, we can merge this.

**Comment by mikropsoft** [comment]
> Thanks for providing additional files. I've added escaping for special characters ([docs](https://developer.android.com/guide/topics/resources/string-resource#FormattingAndStyling)), removed redundant non-translatable strings, and made some minor fixes. You can verify if everything is okay; if so, we can merge this.

Done 💯

**Comment by aleksey-saenko** [comment]
Merged. Thanks for your contribution!

**Comment by aleksey-saenko** [comment]
@mikropsoft 
Hi there! The app is now hosted on [Weblate](https://hosted.weblate.org/projects/audile/). If you have a moment to update the translation, I would greatly appreciate it.

**Pull request merged**
